### ISSUE TITLE
tutorial series suggestions

### ISSUE THREAD

**Issue by friuns2** [Endarren/Unity_Resources#2]
Video
mix and jam https://www.youtube.com/channel/UCLyVUwlB_Hahir_VsKkGPIA
Sebastian Lague https://www.youtube.com/user/Cercopithecan
The art of code  https://www.youtube.com/channel/UCcAlTqd9zID6aNX3TzwxJXg
Makin' Stuff Look Good https://www.youtube.com/channel/UCEklP9iLcpExB8vp_fWQseg

Text
https://catlikecoding.com/unity/tutorials/

in Russian language
https://www.youtube.com/channel/UC6wnai488mwec_FUVfdl84w

**Comment by Endarren** [comment]
Sorry for not seeing this earlier.  I will get on it.
